// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    CalendarDemo: typeof import('./src/components/CalendarDemo.vue')['default']
    InputComponent: typeof import('./src/components/InputComponent.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Paypal: typeof import('./src/components/Paypal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
